# this jinja2 template is filled out by process.py to build mkdocs.yml
site_name: Use Case Library v1.0
pages:
  - Introduction: index.md
  - Use Case Summaries:
{% for obj in yield_objects('SUMMARY') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - User Narratives:
{% for obj in yield_objects('NARRATIVE') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Personas:
{% for obj in yield_objects('PERSONA') %}
    - "{{ obj.title }}": {{ obj.ident }}.md
{% endfor %}
  - User Stories:
{% for obj in yield_objects('USER STORY') %}
    - "{{ obj.title }}": {{ obj.ident }}.md
{% endfor %}
  - Epics:
{% for obj in yield_objects('EPIC') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Complete List of Contents: full_list.md


theme:
  name: null
  custom_dir: 'mkdocs-material-dib/material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'dns'
  font:
    text: 'Roboto Slab'
    code: 'Roboto Mono'

# Extensions
#markdown_extensions:
#  - admonition
#  - codehilite:
#      guess_lang: false
#  - toc:
#      permalink: true

extra:
  # annotation
  hypothesis: true
  # disqus
#  disqus: dcppc-internal
