# this jinja2 template is filled out by process.py to build mkdocs.yml
site_name: Use Case Library v1.0
site_url: http://nih-data-commons.us/use-case-library
base_url: http://nih-data-commons.us/use-case-library

copyright: 'This website is available under the terms of the 
<a href="https://creativecommons.org/licenses/by/4.0/">CC-BY license</a>.<br />'

pages:
  - Introduction: index.md
  - Use Case Summaries:
{% for obj in yield_objects('SUMMARY') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - User Narratives:
{% for obj in yield_objects('NARRATIVE') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Personas:
{% for obj in yield_objects('PERSONA') %}
    - "{{ obj.title }}": {{ obj.ident }}.md
{% endfor %}
  - User Stories:
{% for obj in yield_objects('USER STORY') %}
    - "{{ obj.title }}": {{ obj.ident }}.md
{% endfor %}
  - Epics:
{% for obj in yield_objects('EPIC') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Complete List of Contents: full_list.md
  - Glossary of terms: glossary.md

theme:
  name: null
  custom_dir: 'mkdocs-material-dib/material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo: 'images/dcppc-logo.png'
  font:
    text: 'Roboto Slab'
    code: 'Roboto Mono'

# Extensions
#markdown_extensions:
#  - admonition
#  - codehilite:
#      guess_lang: false
#  - toc:
#      permalink: true

extra:
  # annotation
  hypothesis: true
  # disqus
  disqus: data-commons-use-case-library
